// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Types
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';

// User Types
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const SELECT_ALL_USERS = 'SELECT_ALL_USERS';
export const SELECT_USER = 'SELECT_USER';
export const TOGGLE_USER_DIALOG = 'TOGGLE_USER_DIALOG';

// Movie Types
export const GET_MOVIES = 'GET_MOVIES';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';

// Cinema Types
export const GET_CINEMAS = 'GET_CINEMAS';
export const GET_CINEMA = 'GET_CINEMA';

// Showtime Types
export const GET_SHOWTIMES = 'GET_SHOWTIMES';
export const DELETE_SHOWTIME = 'DELETE_SHOWTIME';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const SELECT_SHOWTIMES = 'SELECT_SHOWTIMES';
export const SELECT_ALL_SHOWTIMES = 'SELECT_ALL_SHOWTIMES';

// Reservation Types
export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const GET_RESERVATION_SUGGESTED_SEATS = 'GET_RESERVATION_SUGGESTED_SEATS';

// Checkout Types
export const SET_SELECTED_SEATS = 'SET_SELECTED_SEATS';
export const SET_SUGGESTED_SEATS = 'SET_SUGGESTED_SEATS';
export const SET_SELECTED_CINEMA = 'SET_SELECTED_CINEMA';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_SELECTED_TIME = 'SET_SELECTED_TIME';
export const SET_INVITATION = 'SET_INVITATION';
export const TOGGLE_LOGIN_POPUP = 'TOGGLE_LOGIN_POPUP';
export const SHOW_INVITATION_FORM = 'SHOW_INVITATION_FORM';
export const RESET_CHECKOUT = 'RESET_CHECKOUT';
export const SET_QR_CODE = 'SET_QR_CODE';

// Modal and Form Types
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL';
export const HIDE_REGISTER_MODAL = 'HIDE_REGISTER_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';
export const SET_TICKET_PRICE = 'SET_TICKET_PRICE';
export const CONFIRM_BOOKING = 'CONFIRM_BOOKING';
export const BOOKING_ERROR = 'BOOKING_ERROR';
export const CLEAR_CHECKOUT = 'CLEAR_CHECKOUT';
export const SET_BOOKING_STEP = 'SET_BOOKING_STEP';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';
export const VALIDATE_BOOKING = 'VALIDATE_BOOKING';
export const RESERVATION_ERROR = 'RESERVATION_ERROR';
export const CLEAR_RESERVATION = 'CLEAR_RESERVATION';
export const SET_RESERVATION_STATUS = 'SET_RESERVATION_STATUS';
export const GET_USER_RESERVATIONS = 'GET_USER_RESERVATIONS';
export const CANCEL_RESERVATION = 'CANCEL_RESERVATION';
export const USER_ERROR = 'USER_ERROR';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const SHOWTIME_ERROR = 'SHOWTIME_ERROR';
export const CLEAR_SHOWTIME = 'CLEAR_SHOWTIME';
export const SET_SHOWTIME_AVAILABILITY = 'SET_SHOWTIME_AVAILABILITY';
export const FILTER_SHOWTIMES = 'FILTER_SHOWTIMES';
export const ADD_SHOWTIME = 'ADD_SHOWTIME';
export const UPDATE_SHOWTIME = 'UPDATE_SHOWTIME';
export const ADD_CINEMA = 'ADD_CINEMA';
export const UPDATE_CINEMA = 'UPDATE_CINEMA';
export const DELETE_CINEMA = 'DELETE_CINEMA';
export const CINEMA_ERROR = 'CINEMA_ERROR';
export const CLEAR_CINEMA = 'CLEAR_CINEMA';
export const SET_CINEMA_SEATS = 'SET_CINEMA_SEATS';
export const SET_CINEMA_SCHEDULE = 'SET_CINEMA_SCHEDULE';
export const SET_CINEMA_FACILITIES = 'SET_CINEMA_FACILITIES';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const MOVIE_ERROR = 'MOVIE_ERROR';
export const CLEAR_MOVIE = 'CLEAR_MOVIE';
export const SET_MOVIE_RATING = 'SET_MOVIE_RATING';
export const SET_MOVIE_REVIEWS = 'SET_MOVIE_REVIEWS';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const SET_MOVIE_CATEGORY = 'SET_MOVIE_CATEGORY'; 